namespace Turbo.Runtime
{
	public enum CmdLineError
	{
		NoError,
		AssemblyNotFound = 2001,
		CannotCreateEngine,
		CompilerConstant,
		DuplicateFileAsSourceAndAssembly,
		DuplicateResourceFile,
		DuplicateResourceName,
		DuplicateSourceFile,
		ErrorSavingCompiledState,
		IncompatibleTargets = 2038,
		InvalidAssembly = 2009,
		InvalidCharacters = 2036,
		InvalidCodePage = 2010,
		InvalidDefinition,
		InvalidForCompilerOptions = 2037,
		InvalidLocaleID = 2012,
		InvalidPlatform = 2039,
		InvalidTarget = 2013,
		InvalidSourceFile,
		InvalidVersion = 2031,
		InvalidWarningLevel = 2015,
		ManagedResourceNotFound = 2022,
		MissingDefineArgument = 2018,
		MissingExtension,
		MissingLibArgument,
		MissingReference = 2034,
		MissingVersionInfo = 2021,
		MultipleOutputNames = 2016,
		MultipleTargets,
		MultipleWin32Resources = 2033,
		NestedResponseFiles = 2023,
		NoCodePage,
		NoFileName,
		NoInputSourcesSpecified,
		NoLocaleID,
		NoWarningLevel,
		ResourceNotFound,
		SourceFileTooBig = 2032,
		SourceNotFound = 2035,
		UnknownOption = 2030,
		Unspecified = 2999,
		LAST = 2039
	}
}
