using System.Runtime.InteropServices;

namespace Turbo.Runtime
{
	[ComVisible(true), Guid("268CA962-2FEF-3152-BA46-E18658B7FA4F")]
	public enum TError
	{
		NoError,
		InvalidCall = 5,
		OutOfMemory = 7,
		TypeMismatch = 13,
		OutOfStack = 28,
		InternalError = 51,
		FileNotFound = 53,
		NeedObject = 424,
		CantCreateObject = 429,
		OLENoPropOrMethod = 438,
		ActionNotSupported = 445,
		NotCollection = 451,
		SyntaxError = 1002,
		NoColon,
		NoSemicolon,
		NoLeftParen,
		NoRightParen,
		NoRightBracket,
		NoLeftCurly,
		NoRightCurly,
		NoIdentifier,
		NoEqual,
		IllegalChar = 1014,
		UnterminatedString,
		NoCommentEnd,
		BadReturn = 1018,
		BadBreak,
		BadContinue,
		BadHexDigit = 1023,
		NoWhile,
		BadLabel,
		NoLabel,
		DupDefault,
		NoMemberIdentifier,
		NoCcEnd,
		CcOff,
		NotConst,
		NoAt,
		NoCatch,
		InvalidElse,
		NoComma = 1100,
		DupVisibility,
		IllegalVisibility,
		BadSwitch,
		CcInvalidEnd,
		CcInvalidElse,
		CcInvalidElif,
		ErrEOF,
		IncompatibleVisibility,
		ClassNotAllowed,
		NeedCompileTimeConstant,
		DuplicateName,
		NeedType,
		NotInsideClass,
		InvalidPositionDirective,
		MustBeEOL,
		WrongDirective = 1118,
		CannotNestPositionDirective,
		CircularDefinition,
		Deprecated,
		IllegalUseOfThis,
		NotAccessible,
		CannotUseNameOfClass,
		MustImplementMethod = 1128,
		NeedInterface,
		UnreachableCatch = 1133,
		TypeCannotBeExtended,
		UndeclaredVariable,
		VariableLeftUninitialized,
		KeywordUsedAsIdentifier,
		NotAllowedInSuperConstructorCall = 1140,
		NotMeantToBeCalledDirectly,
		GetAndSetAreInconsistent,
		InvalidCustomAttribute,
		InvalidCustomAttributeArgument,
		InvalidCustomAttributeClassOrCtor = 1146,
		TooManyParameters = 1148,
		AmbiguousBindingBecauseOfWith,
		AmbiguousBindingBecauseOfEval,
		NoSuchMember,
		ItemNotAllowedOnDynamicElementClass,
		MethodNotAllowedOnDynamicElementClass,
		MethodClashOnDynamicElementSuperClass = 1155,
		BaseClassIsDynamicElementAlready,
		AbstractCannotBePrivate,
		NotIndexable,
		StaticMissingInStaticInit,
		MissingConstructForAttributes,
		OnlyClassesAllowed,
		DynamicElementClassShouldNotImpleEnumerable,
		NonCLSCompliantMember,
		NotDeletable,
		PackageExpected,
		UselessExpression = 1169,
		HidesParentMember,
		CannotChangeVisibility,
		HidesAbstractInBase,
		NewNotSpecifiedInMethodDeclaration,
		MethodInBaseIsNotVirtual,
		NoMethodInBaseToNew,
		DifferentReturnTypeFromBase,
		ClashWithProperty,
		OverrideAndHideUsedTogether,
		InvalidLanguageOption,
		NoMethodInBaseToOverride,
		NotValidForConstructor,
		CannotReturnValueFromVoidFunction,
		AmbiguousMatch,
		AmbiguousConstructorCall,
		SuperClassConstructorNotAccessible,
		OctalLiteralsAreDeprecated,
		VariableMightBeUnitialized,
		NotOKToCallSuper,
		IllegalUseOfSuper,
		BadWayToLeaveFinally,
		NoCommaOrTypeDefinitionError,
		AbstractWithBody,
		NoRightParenOrComma,
		NoRightBracketOrComma,
		ExpressionExpected,
		UnexpectedSemicolon,
		TooManyTokensSkipped,
		BadVariableDeclaration,
		BadFunctionDeclaration,
		BadPropertyDeclaration,
		DoesNotHaveAnAddress = 1203,
		TooFewParameters,
		UselessAssignment,
		SuspectAssignment,
		SuspectSemicolon,
		ImpossibleConversion,
		FinalPrecludesAbstract,
		NeedInstance,
		CannotBeAbstract = 1212,
		InvalidBaseTypeForEnum,
		CannotInstantiateAbstractClass,
		ArrayMayBeCopied,
		AbstractCannotBeStatic,
		StaticIsAlreadyFinal,
		StaticMethodsCannotOverride,
		StaticMethodsCannotHide,
		DynamicElementPrecludesOverride,
		IllegalParamArrayAttribute,
		DynamicElementPrecludesAbstract,
		ShouldBeAbstract,
		BadModifierInInterface,
		VarIllegalInInterface = 1226,
		InterfaceIllegalInInterface,
		NoVarInEnum,
		InvalidImport,
		EnumNotAllowed,
		InvalidCustomAttributeTarget,
		PackageInWrongContext,
		ConstructorMayNotHaveReturnType,
		OnlyClassesAndPackagesAllowed,
		InvalidDebugDirective,
		CustomAttributeUsedMoreThanOnce,
		NestedInstanceTypeCannotBeExtendedByStatic,
		PropertyLevelAttributesMustBeOnGetter,
		BadThrow,
		ParamListNotLast,
		NoSuchType,
		BadOctalLiteral,
		InstanceNotAccessibleFromStatic,
		StaticRequiresTypeName,
		NonStaticWithTypeName,
		NoSuchStaticMember,
		SuspectLoopCondition,
		ExpectedAssembly,
		AssemblyAttributesMustBeGlobal,
		DynamicElementPrecludesStatic,
		DuplicateMethod,
		NotAnDynamicElementFunction,
		NotValidVersionString,
		ExecutablesCannotBeLocalized,
		StringConcatIsSlow,
		CcInvalidInDebugger,
		DynamicElementMustBePublic,
		DelegatesShouldNotBeExplicitlyConstructed,
		ImplicitlyReferencedAssemblyNotFound,
		PossibleBadConversion,
		PossibleBadConversionFromString,
		InvalidResource,
		WrongUseOfAddressOf,
		NonCLSCompliantType,
		MemberTypeCLSCompliantMismatch,
		TypeAssemblyCLSCompliantMismatch,
		IncompatibleAssemblyReference,
		InvalidAssemblyKeyFile,
		TypeNameTooLong,
		MemberInitializerCannotContainFuncExpr,
		CantAssignThis = 5000,
		NumberExpected,
		FunctionExpected,
		CannotAssignToFunctionResult,
		StringExpected = 5005,
		DateExpected,
		ObjectExpected,
		IllegalAssignment,
		UndefinedIdentifier,
		BooleanExpected,
		VBArrayExpected = 5013,
		EnumeratorExpected = 5015,
		RegExpExpected,
		RegExpSyntax,
		UncaughtException = 5022,
		InvalidPrototype,
		URIEncodeError,
		URIDecodeError,
		FractionOutOfRange,
		PrecisionOutOfRange,
		ArrayLengthConstructIncorrect = 5029,
		ArrayLengthAssignIncorrect,
		NeedArrayObject,
		NoConstructor,
		IllegalEval,
		NotYetImplemented,
		MustProvideNameForNamedParameter,
		DuplicateNamedParameter,
		MissingNameParameter,
		MoreNamedParametersThanArguments,
		NonSupportedInDebugger,
		AssignmentToReadOnly,
		WriteOnlyProperty,
		IncorrectNumberOfIndices,
		RefParamsNonSupportedInDebugger,
		CannotCallSecurityMethodLateBound,
		CannotUseStaticSecurityAttribute,
		NonClsException,
		FuncEvalAborted = 6000,
		FuncEvalTimedout,
		FuncEvalThreadSuspended,
		FuncEvalThreadSleepWaitJoin,
		FuncEvalBadThreadState,
		FuncEvalBadThreadNotStarted,
		NoFuncEvalAllowed,
		FuncEvalBadLocation,
		FuncEvalWebMethod,
		StaticVarNotAvailable,
		TypeObjectNotAvailable,
		ExceptionFromHResult,
		SideEffectsDisallowed
	}
}
